spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.13.253:3306/sell?characterEncoding=UTF-8&userSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud: 
    stream:
      bindings:
        output:
          group: order
          contentType: application/json
server:
  port: 8081

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
