spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.13.253:3306/sell?characterEncoding=UTF-8&userSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

server:
  port: 8082

# hystrix overtime
hystrix:
  command:
#    default:
#      circuitBreaker:
#        enabled: true
#        requestVolumeThreshold: 10
#        sleepWindowInMilliseconds: 1000
#        errorThresholdPercentage: 60
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

# feign overtime
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#  hystrix:
#    enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: debug

env: zhangsan


