hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

server:
  port: 8081


# spring-cloud-sleuth
logging:
  level: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.13.253:3306/sell?characterEncoding=utf-8&useSSL=false
# spring-cloud-bus-rabbitmq
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

# save product in redis
#  redis:
#    host: 192.168.13.253
#    port: 6379
#  jpa:
#    show-sql: true